name: Send Email on New File

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest commit files
        id: files
        run: |
          echo "FILES=$(git diff --name-only HEAD~1 HEAD)" >> $GITHUB_ENV

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "New File Added in GitHub Repo by krishna baap"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            A new file was added in your repository.

            Files:
            ${{ env.FILES }}
